# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

trigger:
- master

jobs:
  - job: test
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      matrix:
        rails_50:
          RAILS_VERSION: 5.0.7.2
          SQLITE3_VERSION: 1.3.13
        rails_51:
          RAILS_VERSION: 5.1.7
          SQLITE3_VERSION: 1.4.2
        rails_52:
          RAILS_VERSION: 5.2.4.4
          SQLITE3_VERSION: 1.4.2
        rails_60:
          RAILS_VERSION: 6.0.3.3
          SQLITE3_VERSION: 1.4.2
        rails_master:
          RAILS_VERSION: master
          SQLITE3_VERSION: 1.4.2
    steps:
    - task: UseRubyVersion@0
      inputs:
        versionSpec: '>= 2.5'
    - script: |
        sudo apt-get update
        sudo apt-get install libreadline-dev libsqlite3-dev
      displayName: 'Install apt dependencies'
    - script: gem update --system --no-doc
      displayName: 'update rubygems'
    - script: |
        gem install bundler
        bundle install --retry=3 --jobs=4
      displayName: 'bundle install'
    - script: ./bin/rails db:create db:migrate
      displayName: 'prepare database'
    - script: RAILS_ENV=test ./bin/rails test
      displayName: 'run tests'
    - script: RAILS_ENV=test ./bin/rails app:test:system
      displayName: 'run system tests'
